Descripteur_image :  Descripteur_image.c Global.c tst_descripteur_image.c 
	gcc -c Global.c 
	gcc -c Descripteur_image.c
	gcc -c tst_descripteur_image.c
	gcc -o tst_descripteur_image.exe Global.o Descripteur_image.o tst_descripteur_image.o -lm
	gcc -o tst_descripteur_image.out Global.o Descripteur_image.o tst_descripteur_image.o -lm