RechercheMot : rechercheTexte.c rechercheTexte.h tstRechercheTexte.c
	gcc -c rechercheTexte.c
	gcc -c tstRechercheTexte.c
	gcc -o RechercheMot.out rechercheTexte.o tstRechercheTexte.o
	./RechercheMot.out
	
clean : 
	rm -rf *.o