Config : Config.c Global.c tst_config.c 
	gcc -c Config.c 
	gcc -c Global.c 
	gcc -c tst_config.c
	gcc -o tst_Config.exe Config.o Global.o tst_Config.o -lm
	gcc -o tst_Config.out Config.o Global.o tst_Config.o -lm