descripteur_audio : descripteur_audio.c
	gcc -c descripteur_audio.c 
	gcc -c test_descripteur_audio.c
	gcc -o test_descripteur_audio.out descripteur_audio.o test_descripteur_audio.o
	
clean :
	rm -rf *.o
