Comparaison_image :  Comparaison_image.c tst_comparaison_img.c
	gcc -c Comparaison-image.c
	gcc -c tst_comparaison_img.c
	gcc -o tst_comparaison_img.exe ../../Descripteur-image/src/Global.o ../../Descripteur-image/src/Descripteur_image.o tst_comparaison_img.o Comparaison-image.o -lm
	gcc -o tst_comparaison_img.out ../../Descripteur-image/src/Global.o ../../Descripteur-image/src/Descripteur_image.o tst_comparaison_img.o Comparaison-image.o -lm
