Descripteur_image :  Descripteur_image.c tst_descripteur_image.c 
	gcc -c Descripteur_image.c
	gcc -c tst_descripteur_image.c
	gcc -o tst_descripteur_image.exe Descripteur_image.o tst_descripteur_image.o -lm
	gcc -o tst_descripteur_image.out Descripteur_image.o tst_descripteur_image.o -lm