Descripteur_texte : Config.c Global.c descripteur_texte.c test_descipteur_texte.c descripteur_texte.h
	gcc -c descripteur_texte.c
	gcc -c test_descipteur_texte.c
	gcc -o descripteur_texte.exe Config.o Global.o descripteur_texte.o test_descipteur_texte.o -lm
	rm -rf *.o
	./descripteur_texte.exe