comparaison_audio : comparaison_audio.c comparaison_audio.h ../descripteur_audio/descripteur_audio.c
	gcc -c comparaison_audio.c 
	gcc -o comparaison_audio.out comparaison_audio.o ../descripteur_audio/descripteur_audio.o
